version: '3.7'

x-demo: &demo
  image: demo
  env_file:
    - .env
  environment:
    - FLASK_APP=run.py
    - FLASK_CONFIG=development
    - PYTHONUNBUFFERED=true
  networks:
    - demo
  # volumes:
  #   - ./:/backend

services:
  database:
    image: postgres:10.6
    ports:
      - '5440:5432'
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    volumes:
      - demodb:/var/lib/postgresql/data
    networks:
      - demo
  web:
    ports:
      - '5000:5000'
    # restart: always
    depends_on:
      - database
    entrypoint:
      - /backend/boot.sh
    <<: *demo

volumes:
  demodb:

networks:
  demo:
    driver: bridge
